### ISSUE TITLE
access stream on laptop via usb

### ISSUE THREAD

**Issue by jhachandan1994** [dkrivoruchko/ScreenStream#116]
is it possible to access the video stream by connecting the device using usb and if both device and laptop are on different network.

**Comment by rugk** [comment]
Yes, it is, because you can use `adb` to forward network sockets. So:
1. Enable "listen on localhost" in the settings ("advanced" section) of this app. (You can even disable anything else.)
2. Run `adb forward tcp:8080 tcp:8080` (syntax: `adb forward tcp:LOCAL tcp:DEVICE`) or another port you have set in the settings to forward the connection.
3. Now you can access this on your computer with `127.0.0.1:8080`.

Run `adb forward --remove-all` to remove that again.

**Comment by jhachandan1994** [comment]
thanks @rugk it's working now. i was missing the listen on localhost settings part.
