### ISSUE TITLE
No longer compatible with ereaders?

### ISSUE THREAD

**Issue by vspinu** [dkrivoruchko/ScreenStream#271]
First of all, thanks a ton for this app!!! There is literally no viable alternative for my use case. I use it to share papers and books during my meetings from an e-reader.

Unfortunately after the recent upgrade on my boox-tab10 reader (android 11) the app is no longer available for this device from the apps store.

It worked almost perfectly so far. Was this by design? And if so, is there anything I could do except of directly hacking on the app? 

Thanks!

**Comment by dkrivoruchko** [comment]
Hey. Last versions are allowed to be installed on devices that pass certain security & compatibility checks. 

[Device integrity checks] - Google Play will check the device meets device integrity before making your app visible to users.

The reason is that WebRTC mode (Global mode) require Device integrity checks to pass for user been able to use it.

You can install the latest app as .apk from [Releases](https://github.com/dkrivoruchko/ScreenStream/releases) 

If you use only MJPEG mode (Local mode) - use app from [F-Droid](https://f-droid.org/packages/info.dvkr.screenstream/)

**Comment by vspinu** [comment]
Indeed, my ereader is bought from china, so probably not cutting it to the full integrity specs :( 

I need it for MJPEG only, and F-Droid version is just perfect! Thanks a bunch!!!
